name: build caddy

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "linux-amd64",
            GOARCH: amd64,
            GOOS: linux,
            release: true
          }
        - {
            name: "linux-arm64",
            GOARCH: arm64,
            GOOS: linux,
            release: true
          }

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.23.1'
          check-latest: true
      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build
        run: |
          export GOARCH=${{ matrix.config.GOARCH }}
          export GOOS=${{ matrix.config.GOOS }}
          ~/go/bin/xcaddy build \
            --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive \
            --with github.com/imgk/caddy-trojan \
          
      - name: Tar
        run: |
          tar -zcvf ./caddy-${{ matrix.config.GOARCH }}.tar.gz ./caddy

      - name: Upload assets
        if: ${{ github.event_name == 'release' }}
        run: gh release upload "${GITHUB_REF##*/}" caddy-${{ matrix.config.GOARCH }}.tar.xz --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
