name: build caddy

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "linux-amd64"
            GOARCH: amd64
            GOOS: linux
          - name: "linux-arm64"
            GOARCH: arm64
            GOOS: linux
            
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.23.1'
          check-latest: true
      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build
        run: |
          export GOARCH=${{ matrix.GOARCH }}
          export GOOS=${{ matrix.GOOS }}
          ~/go/bin/xcaddy build \
            --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive \
            --with github.com/imgk/caddy-trojan \
          
      - name: Tar
        run: |
          tar -zcvf ./caddy-${{ matrix.GOARCH }}.tar.gz ./caddy

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: caddy-${{ matrix.GOARCH }}.tar.gz
          asset_name: caddy-${{ matrix.GOARCH }}.tar.gz
          overwrite: true
          tag: ${{ github.ref }}
