name: build caddy

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
      - name: Build
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
      - uses: EndBug/add-and-commit@v8
        with:
          add: 'caddy'
          author_name: 'github_action'
